apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: github-runner-scaler
  namespace: gh-runner
spec:
  scaleTargetRef:
    name: github-runner
  minReplicaCount: 0 # Scale to zero when no jobs
  maxReplicaCount: 5 # Adjust based on your needs and cluster capacity
  pollingInterval: 30 # Check every 30 seconds
  cooldownPeriod: 300 # Wait 5 minutes before scaling down
  triggers:
    - type: github-runner
      metadata:
        # Organization-level configuration
        owner: "vvxluster"
        runnerScope: "org" # or "repo" for repository level

        # Repository-level configuration (alternative to org)
        # repos: "repo1,repo2"  # Comma-separated list
        # runnerScope: "repo"

        labels: "gh-keda-runner" # Must match LABELS in deployment
        targetWorkflowQueueLength: "1" # Scale up for each queued job
      authenticationRef:
        name: github-auth-trigger
